---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpressdb.cnjw85jacdlf.eu-west-3.rds.amazonaws.com:3306"
        - name: WORDPRESS_DB_PASSWORD
          value: "mypassword"
        - name: WORDPRESS_DB_USER
          value: "wordpressuser"
        - name: WORDPRESS_DB_NAME
          value: "wordpressdb"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
